using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CallScript : MonoBehaviour
{
    /// <summary>
    /// Variables:
    /// 
    ///     shape: designates shape of the call plug
    ///     pointValue: generated by Player script
    ///     
    ///     callTimePassed: time passed since the call was successfully taken
    ///     callTime: predesignated time for the call to complete; generated by Player script
    ///     
    ///     callExpireTimePassed: amount of time the call has been ignored for
    ///     callExpireTime: Maximum amount of time the call is allowed to be ignored before disappearing
    ///     
    ///     callTaken: switch which shows whether the call is currently being taken
    /// 
    ///     incomingCallPos: position on the switchboard where the call comes in
    ///     
    /// </summary>

    private GameObject shape;
    private int pointValue;

    private float callTimePassed;
    private float callTime;

    private float callExpireTimePassed;
    private float callExpireTime;

    private bool callTaken;

    private Vector2 incomingCallPos;

    public Player player;



    //Properties
    public GameObject Shape
    {
        get { return shape; }
        set { shape = value; }
    }

    public float CallTimePassed
    {
        get { return callTimePassed; }
        set { callTimePassed = value; }
    }

    public float CallTime
    {
        get { return callTime; }
        set { callTime = value; }
    }

    public float CallExpireTime
    {
        get { return callExpireTime; }
        set { callExpireTime = value; }
    }
    public float CallExpireTimePassed
    {
        get { return callExpireTimePassed; }
        set { callExpireTimePassed = value; }
    }
    public int PointValue
    {
        get { return pointValue; }
        set { pointValue = value; }
    }

    public bool CallTaken
    {
        get { return callTaken; }
        set { callTaken = value; }
    }


	// Use this for initialization
	void Start ()
    {
        callTimePassed = 0;
        callExpireTimePassed = 0;
	}
	
	// Update is called once per frame
	void Update ()
    {

        if (callTaken)
        {
            CallTimePassed += Time.deltaTime;

            //If the call was successfully finished, call disappears and updates score
            if (CallTimePassed == CallTime)
            {

            }
        }
        else
        {
            CallExpireTimePassed += Time.deltaTime;

            //If time for the call to be taken expires, player loses a life and call disappears
            if (CallExpireTimePassed == CallExpireTime)
            {

            }
        }



	}
}
